# Generated by Django 4.2.5 on 2023-10-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
