# Generated by Django 4.2.5 on 2023-10-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProjectApp', '0002_delete_about_delete_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='Description',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='Level',
            field=models.PositiveIntegerField(),
        ),
    ]
